# Generated by Django 3.1.2 on 2020-10-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('typeOfIns', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
            ],
        ),
    ]
