# Generated by Django 3.1.2 on 2020-10-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201012_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('addr', models.TextField()),
                ('pno', models.PositiveSmallIntegerField()),
                ('timing', models.CharField(max_length=100)),
                ('closedOn', models.CharField(max_length=100)),
                ('mapLink', models.CharField(max_length=100)),
            ],
        ),
    ]
